// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum meanElementTheory {
  /**
   * Simplified General Perturbation Model 4
   */
  SGP4 = 0,

  /**
   * Draper Semi-analytical Satellite Theory
   */
  DSST = 1,

  /**
   * Universal Semianalytical Method
   */
  USM = 2
}
