export class CatalogEntityMetadata {
  //ALL_PROP: string
  APOGEE: number
  ARG_OF_PERICENTER: number
  BSTAR: number
  //CHECKSUM: number
  //CLASSIFICATION_TYPE: string
  DECAY_DATE: string
  ECCENTRICITY: number
  ELEMENT_SET_NO: number
  EPHEMERIS_TYPE: number
  EPOCH: string
  INCLINATION: number
  LAUNCH_DATE: string
  LAUNCH_SITE: string
  MEAN_ANOMALY: number
  MEAN_MOTION: number
  MEAN_MOTION_DDOT: number
  MEAN_MOTION_DOT: number
  //MULTIPLE_NAMES: boolean
  NORAD_CAT_ID: number
  OBJECT_ID: string
  OBJECT_NAME: string
  OPS_STATUS_CODE: any
  //ORBITAL_STATUS_CODE: any
  //ORBIT_CENTER: number
  //ORBIT_TYPE: any
  OWNER: string
  PAYLOAD: boolean
  PERIGEE: number
  PERIOD: number
  RA_OF_ASC_NODE: number
  RCS: number
  REV_AT_EPOCH: number
  TYPE: number
  OBJECT_TYPE: string
  DATA_SOURCE: string
}
