// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum manCovRefFrame {
  /**
   * Another name for 'Radial, Transverse, Normal'
   */
  RSW = 0,

  /**
   * Radial, Transverse, Normal
   */
  RTN = 1,

  /**
   * A local orbital coordinate frame
   */
  TNW = 2
}
