// automatically generated by the FlatBuffers compiler, do not modify

/**
 * Enum for the mode of data (real, simulated, synthetic)
 */
export enum DataMode {
  real = 0,
  simulated = 1,
  synthetic = 2
}
