// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { SEN, SENT } from './SEN.js';


/**
 * Collection of SEN records
 */
export class SENCOLLECTION implements flatbuffers.IUnpackableObject<SENCOLLECTIONT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SENCOLLECTION {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSENCOLLECTION(bb:flatbuffers.ByteBuffer, obj?:SENCOLLECTION):SENCOLLECTION {
  return (obj || new SENCOLLECTION()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSENCOLLECTION(bb:flatbuffers.ByteBuffer, obj?:SENCOLLECTION):SENCOLLECTION {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SENCOLLECTION()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

RECORDS(index: number, obj?:SEN):SEN|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new SEN()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

recordsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startSENCOLLECTION(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addRecords(builder:flatbuffers.Builder, RECORDSOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, RECORDSOffset, 0);
}

static createRecordsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startRecordsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endSENCOLLECTION(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSENCOLLECTION(builder:flatbuffers.Builder, RECORDSOffset:flatbuffers.Offset):flatbuffers.Offset {
  SENCOLLECTION.startSENCOLLECTION(builder);
  SENCOLLECTION.addRecords(builder, RECORDSOffset);
  return SENCOLLECTION.endSENCOLLECTION(builder);
}

unpack(): SENCOLLECTIONT {
  return new SENCOLLECTIONT(
    this.bb!.createObjList<SEN, SENT>(this.RECORDS.bind(this), this.recordsLength())
  );
}


unpackTo(_o: SENCOLLECTIONT): void {
  _o.RECORDS = this.bb!.createObjList<SEN, SENT>(this.RECORDS.bind(this), this.recordsLength());
}
}

export class SENCOLLECTIONT implements flatbuffers.IGeneratedObject {
constructor(
  public RECORDS: (SENT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const RECORDS = SENCOLLECTION.createRecordsVector(builder, builder.createObjectOffsetList(this.RECORDS));

  return SENCOLLECTION.createSENCOLLECTION(builder,
    RECORDS
  );
}
}
