// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export { ContactPoint, ContactPointT } from './ContactPoint.js';
export { CryptoKey, CryptoKeyT } from './CryptoKey.js';
export { Occupation, OccupationT } from './Occupation.js';
export { Organization, OrganizationT } from './Organization.js';
export { UPM, UPMT } from './UPM.js';
export { UPMCOLLECTION, UPMCOLLECTIONT } from './UPMCOLLECTION.js';
